name: 'SSH to HTTPS action'

description: 'Github Action to reconfigure git to use HTTPS authentication instead of SSH'

inputs:
    github_token:
        description: 'Github Personal Access Token'
        required: false

runs:
  using: "composite"
  steps:

    - name: Reconfigure git to use HTTP authentication
      run: |
        # github.server_url contains https:// prefix, which we need to remove
        server_url=$(echo ${{ github.server_url }} | sed 's/https:\/\///')
        if [ -z "${{ inputs.github_token }}" ]; then
          git config --global url."https://${server_url}/".insteadOf git@${server_url}:
        else
          git config --global url."https://basic:${{ inputs.github_token }}@${server_url}/".insteadOf git@${server_url}:
        fi
      shell: bash

branding:
    icon: 'terminal'
    color: 'black'
